Flask/Aplicacion/models.py
from Aplicacion import db

class TipoUsuarios(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    tipo = db.Column(db.String(100), nullable=False)

    usuarios = db.relationship('Usuarios', backref='tipo', lazy='dynamic')

    def __init__(self, tipo):
        self.tipo = tipo


class Usuarios(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    nombre = db.Column(db.String(50))
    passwrd = db.Column(db.String(50))
    tipoID = db.Column(db.Integer, db.ForeignKey('tipo_usuarios.id'))

    cursos = db.relationship('Cursos', secondary='cursos_usuarios', backref='usuarios', lazy='dynamic')

    def __init__(self, nombre, email, passwrd):
        self.nombre = nombre
        self.email = email
        self.passwrd = passwrd

    def __repr__(self):
        return f"id {self.id} nombre {self.nombre} email {self.email}"

class Cursos(db.Model):
    id = db.Column(db.Integer, primary_key=True, nullable=False)
    curso = db.Column(db.String(50))

    def __init__(self, curso):
        self.curso = curso

    def __repr__(self):
        return f"id {self.id} curso {self.curso}"

db.Table('cursos_usuarios',
    db.Column('usuarioID', db.Integer, db.ForeignKey('usuarios.id')),
    db.Column('cursoID', db.Integer, db.ForeignKey('cursos.id'))
)

Flask/Aplicacion/formularios/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, PasswordField, BooleanField, DecimalField, SubmitField, FileField
from wtforms.validators import DataRequired, Email, EqualTo
from wtforms import ValidationError
from wtforms.widgets import TextArea
from wtforms.widgets.html5 import NumberInput

# Cada clase va a ser un formulario, tiene herencia de FlaskForm
class Prueba(FlaskForm):
    usuario = StringField('Usuario')
    nombre = StringField('Nombre', validators=[DataRequired(message="nombre requerido")])
    descripcion = StringField('Descripcion', widget=TextArea())
    cantidad = DecimalField('Cantidad', widget=NumberInput())
    submit = SubmitField('Ok')

Flask/Aplicacion/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

app = Flask(__name__)

app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://sql3354595:7Haz6Ng1fm@sql3.freemysqlhosting.net/sql3354595'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
app.config['SECRET_KEY'] = 'mysecret'

db = SQLAlchemy(app)
Migrate(app, db)
from Aplicacion.models import *

from Aplicacion.core.views import core
from Aplicacion.usuarios.views import usuarios
from Aplicacion.bases.views import bases
from Aplicacion.formularios.views import formularios


app.register_blueprint(core)
app.register_blueprint(bases)
app.register_blueprint(usuarios, url_prefix='/usuarios')
app.register_blueprint(formularios)

Flask/Aplicacion/bases/views.py
from flask import Blueprint, render_template

bases = Blueprint('bases', __name__)

@bases.route('/venv')
def venv():
    return render_template('venv.html')

@bases.route('/rutas/<string:nombre>')
def rutas(nombre):
    return render_template('rutas.html', nombre=nombre)

@bases.route('/debug')
def debug():
    return render_template('debug.html')

@bases.route('/blueprints')
def blueprints():
    return render_template('blueprints.html')

Flask/Aplicacion/core/views.py
from flask import Blueprint, render_template

core = Blueprint('core', __name__)

@core.route('/')
def index():
    return render_template('index.html')

Flask/Aplicacion/formularios/views.py
from flask import Blueprint, render_template, request
from Aplicacion.formularios.forms import Prueba

formularios = Blueprint('formularios', __name__)

@formularios.route('/formularios', methods=['GET','POST'])
def formulario():
    form = Prueba()
    if request.method == "POST" and form.validate_on_submit():
        return "Muy bien campeon"
    return render_template('formularios.html', form=form)

Flask/Aplicacion/usuarios/views.py
from flask import Blueprint

usuarios = Blueprint('usuarios', __name__)

@usuarios.route('/')
def index():
    return 'En usuarios'

Flask/Aplicacion/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
  {% block styles %}
  {% endblock styles %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <img src="{{ url_for('static', filename='img/flask-logo.png') }}" alt="Logo de Flask" width="120" height="50">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('core.index') }} ">Home<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Temas
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{ url_for('bases.venv') }}">Virtual enviroment y Pip</a>
          <a class="dropdown-item" href="{{ url_for('bases.rutas', nombre='nombre') }}">Rutas</a>
          <a class="dropdown-item" href="{{ url_for('bases.debug') }}">Debug</a>
          <a class="dropdown-item" href="{{ url_for('bases.blueprints') }}">Templates</a>
          <a class="dropdown-item" href="{{ url_for('bases.blueprints') }}">Blueprint</a>
          <a class="dropdown-item" href="#">WTForms</a>
          <a class="dropdown-item" href="#">SQLAchemy</a>
          <a class="dropdown-item" href="#">Flask-Login</a>
          <a class="dropdown-item" href="#">Deploy en Heroku</a>
        </div>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container-fluid contenido">
  {% block content %}
  {% endblock content %}
  </div>
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  {% block scripts %}
  {% endblock scripts %}
</body>
</html>

Flask/Aplicacion/templates/blueprints.html
{% extends 'base.html' %}

{% block styles %}
  <title>Templates y blueprints</title>
{% endblock styles %}

{% block content %}
  <h2>Templates y blueprints</h2>
  <h4>Templates</h4>
  <p>
    En flask un template se puede renderear con el render_template de flask, este automaticamente va a buscar
    una carpeta llamada templates, en el mismo nivel de nuestro archivo, y dentro de la carpeta va buscar el archivo requerido.
  </p>
  <pre>
    <code>
      from flask import Flask, render_template

      app = Flask(__name__)

      @app.route('/')
      def index():
          return render_template('index.html')
    </code>
  </pre>
  <p>
    Flask maneja Jinja2, este tipo de diseño de template nos va a permitir hacer for, if, tener variables y
    otro tipo de estructuras de control, ademas de poder tener herencias y bloques de html separado.
  </p>
  <p>
    La extencion de un template nos ayuda a que si queremos que algo de html este en todas nuestras paginas
    no tengamos que extender el mismo codigo, por ejemplo vamos a extender un navbar de bootstrap a todas nuestras paginas y crear bloques:
  </p>
  <pre>
    <h4>Dentro de base.html</h4>
    <code>
      &lt;!DOCTYPE html&gt;
      &lt;html lang="en"&gt;
      &lt;head&gt;
        &lt;meta charset="UTF-8"&gt;
        &lt;meta name="viewport" content="width=device-width, initial-scale=1.0"&gt;
        &lt;link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"&gt;
        <!-- raw es para poder poner codigo de Jinja2 sin que sea interpretado como codigo -->
        {%- raw -%}
        {% block cabeza %}
          
        {% endblock cabeza %}
        {%- endraw %}
      &lt;/head&gt;
      &lt;body&gt;
        &lt;nav class="navbar navbar-expand-lg navbar-light bg-light"&gt;
          &lt;a class="navbar-brand" href="#"&gt;Navbar&lt;/a&gt;
          &lt;button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"&gt;
            &lt;span class="navbar-toggler-icon"&gt;&lt;/span&gt;
          &lt;/button&gt;
          &lt;div class="collapse navbar-collapse" id="navbarNav"&gt;
            &lt;ul class="navbar-nav"&gt;
              &lt;li class="nav-item active"&gt;
                &lt;a class="nav-link" href="#"&gt;Home &lt;span class="sr-only"&gt;(current)&lt;/span&gt;&lt;/a&gt;
              &lt;/li&gt;
            &lt;/ul&gt;
          &lt;/div&gt;
        &lt;/nav&gt;
        {% raw -%}
        {% block contenido %}
          
        {% endblock contenido %}
        {%- endraw %}
        &lt;script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"&gt;&lt;/script&gt;
        &lt;script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"&gt;&lt;/script&gt;
        &lt;script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"&gt;&lt;/script&gt;
      &lt;/body&gt;
      &lt;/html&gt;
    </code>
    <h4>Dentro de index.html</h4>
    <code>
      {% raw -%}
      {% extends 'base.html' %}

      {% block cabeza %}
      &lt;title&gt;Mi pagina&lt;/title&gt;
      {% endblock cabeza %}

      {% block contenido %}
      &lt;div&gt;El contenido va aqui&lt;/div&gt;
      {% endblock contenido %}
      {%- endraw -%}
    </code>
  </pre>
  <p>
    De esta manera ya incluimos las librerias de bootstrap a nuestros templates asi como tambien la navbar. Con los
    bloques dejamos espacio en &lt;head&gt; para poner titulo, colocar otros archivos ccs entre otras cosas, ademas dejamos en
    &lt;body&gt; otro bloque abierto para nuestro contendo de esa pagina. Y el archivo que se llama en render_template es index.html.
  </p>
   Todo esto se va a ver mas a profundidad mas adelante, en especial con la base de datos y flask-login. Aqui el link a la documentacion.
   <br>
  <a href="https://jinja.palletsprojects.com/en/2.11.x/templates/#">Documentacion a Jinja2</a>
  <br>
  <br>
  <h4>Blueprints</h4>
  <p>
    Los blueprints ya vienen instalados con flask, estos nos ayudan a organizar mejor grandes aplicaciones
    en vez de tener todo en un archivo grande. Primero tenemos que crear una carpeta con un nombre significativo, por
    ejemplo si ahi vamos a manejar todo el backend del usuariole podemos llamar usuario a la carpeta, esta carpeta se crea en
    el mismo nivel que nuestro __init__.py de la aplicacion.
  </p>
  <pre>
    <img src="{{ url_for('static', filename='img/blueprint1.png') }}" alt="blueprint">
  </pre>
  <p>
    Dentro de esa carpeta vamos a abrir un archivo llamado views.py donde vamos a
    organizar todas las vistas de los usuarios. Dentro de views.py vamos a escribir lo siguiente:
  </p>
  <pre>
    Dentro de aplicacion\aplicacion\usuarios\views.py
    <code>
      from flask import Blueprint

      # Por lo general la instancia y el nombre del blueprint es el mismo para que no haya confusion
      usuarios = Blueprint('usuarios', __name__)

      # Como ya no estamos en un solo archivo las rutas se definen con el blueprint
      @usuarios.route('/')
      def usuario():
          return "En usuarios"
    </code>
    <h5>Ya que creamos el blueprint lo tenemos que registrar en __init__.py de la aplicacion</h5>
    Dentro de aplicacion\aplicacion\__init__.py
    <code>
      from flask import Flask

      app = Flask(__name__)

      # Este import se hace aqui ya que primero se debe de crear la aplicacion y luego se instancia el blueprint
      from aplicacion.usuarios.views import usuarios

      app.register_blueprint(usuarios)
    </code>
  </pre>
  <p>
    Tambien se le puede definir un prefijo que vaya en todas las paginas del blueprint, 
    todo el codigo es igual nada mas que en la instancia se define el prefijo:
  </p>
  <pre>
    <code>
      admin = Blueprint('admin', __name__, url_prefix='/admin')
    </code>
  </pre>
  <p>
    De esta manera cualquier pagina que se agregue en este blueprint sera el.dominio.com/admin/nombre-ruta
  </p>
{% endblock content %}

Flask/Aplicacion/templates/debug.html
{% extends 'base.html' %}

{% block styles %}
  <title>Debug</title>
{% endblock styles %}

{% block content %}
  <h2>Debug</h2>
  <p>
    Con lo que se ha visto si la aplicacion llega a tener un error en estos momentos no sabriamos cual es,
    ya que si hay algun error solo muestra una pagina en blanco o incluso si hacemos algun cambio probablemente la pagina no se va actualizar.
    Para lograr esto hay que activar el modo debug poniendo el modo debug en true cuando la corremos (este cambio se hace en el archivo app.py):
  </p>
  <pre>
    <code>
      if __name__ == "__main__":
          app.run(debug=True)
    </code>
  </pre>
  <p>
    De esta manera cuando haya un error nos debera aparecer una pagina como esta:
  </p>
  <pre>
    <img src="{{ url_for('static', filename='img/error.png') }}" alt="Ejemplo error" width="1180" height="700">
  </pre>
  <p>
    Por ejemplo en la imagen de arriba nos dice que el archivo debu.html no se encontro, si seguimos scroleando para abajo podemos encontrar la linea
    exacta en la cual esta el error.
  </p>
  <p>
    Tambien podemos acceder a una pequeña terminal desde la pagina de error clickeando en la terminal hasta la
    derecha de la linea que queremos modificar.
  </p>
  <pre>
    <img src="{{ url_for('static', filename='img/error1.png') }}" alt="Ejemplo error" width="1180" height="700">
  </pre>
  <p>
    Despues nos va a pedir un pin de debugger
  </p>
  <pre>
    <img src="{{ url_for('static', filename='img/error2.png') }}" alt="Ejemplo error" width="500" height="300">
  </pre>
  <p>
    Este pin esta en la terminal
  </p>
  <pre>
    <img src="{{ url_for('static', filename='img/error3.png') }}" alt="Ejemplo error" width="800" height="250">
  </pre>
  <p>
    Lo ponemos y ya podemos modificar lineas de codigo dentro de la pagina de error.
  </p>
  <pre>
    <img src="{{ url_for('static', filename='img/error4.png') }}" alt="Ejemplo error" width="800" height="250">
  </pre>
  <p>
    Cualquier cambio que se hagan NO SE VA A VER REFLEJADO EN NUESTRA APLICACION, cuando acabenmos de debugear
    tendremos que cambiar nuestro archivo para que funcione bien.
  </p>
  <a class="float-right" href="{{ url_for('bases.blueprints') }}">Siguiente Pagina: Blueprint y templates</a>
{% endblock content %}

Flask/Aplicacion/templates/index.html
{% extends 'base.html' %}

{% block styles %}
  <title>Bienvenido</title>
{% endblock %}

{% block content %}
  En esta pagina encontraras las bases de como hacer un aplicacion con flask
  <ul>
    <li> <a href="{{ url_for('bases.venv') }}">Virtual environment</a> </li>
    <li> <a href="{{ url_for('bases.rutas', nombre='nombre') }}">Rutas</a> </li>
    <li> <a href="{{ url_for('bases.debug') }}">Modo debug</a> </li>
    <li> <a href="{{ url_for('bases.blueprints') }}">Templates y blueprints</a> </li>
    <li> <a href="{{ url_for('formularios.formulario') }}">WTForms</a> </li>
    <li> <a href="#">SQLAlchemy</a> </li>
    <li> <a href="#">Flask-login</a> </li>
    <li> <a href="#">Deploy en heroku</a> </li>
  </ul>
{% endblock %}

Flask/Aplicacion/templates/rutas.html
{% extends 'base.html' %}

{% block styles %}
  <title>Rutas</title>
{% endblock styles %}

{% block content %}
  <h2>Rutas</h2>
  <h4>Primer argumento</h4>
  <p>
    Las rutas en flask se manejan con el decorador .route(), estas como minimo deben de llevar un argumento con una barra ('/').
    Estas nos ayudan a definir lo que va a ir en el navegador, todas las rutas al principio deben de llevar la barra, como ahorita el codigo esta pagina es:
  </p>
  <pre>
    <code>
      @app.route('/rutas')
        def rutas():
            ...
            return
    </code>
  </pre>
  <p>
    Por lo que el navegador tendra el.dominio.com/rutas
  </p>
  <p>
    Tambien se le pueden asignar varias rutas a la misma funcion, simplemente acumulando decoradores:
  </p>
  <pre>
    <code>
      @app.route('/')
      @app.route('/home')
      @app.route('/index')
      def index():
          return ...
    </code>
  </pre>
  <p>
    Ya sea a que entres a el.dominio.com/, el.dominio.com/home o el.dominio.com/index, todas van a referirse a la misma pagina.
  </p>
  <h4>Segundo argumento</h4>
  <p>
    El segundo argumento que se le puede especificar al decorador de la ruta es los metodos que puede recibir, por default puede recibir GET pero
    si queremos que reciba otros y ademas GET, este tambien lo tenemos que especificar:
  </p>
  <pre>
    <code>
      @app.route('/bases', methods=['GET','POST','PUT'])
    </code>
  </pre>
  <p>
    Ahora esa ruta puede aceptar GET, POST y PUT.
  </p>
  <h4>Rutas dinamicas</h4>
  <p>
    Ademas podemos tener rutas dinamicas, tenemos que especificarle a la ruta cuantos argumentos
    y que tipo, ademas que la funcion debe de recibir los parametros, de la siguiente manera:
  </p>
  <pre>
    <code>
      @app.route('/rutas/<<x>string:nombre>')
        def rutas(nombre):
            ...
            return
    </code>
  </pre>
  <p>
    De esta manera le estamos pasando nombre como argumento a la funcion, 
    modifica la ruta de arriba por otra cosa que no sea nombre y veras como funciona:
  </p>
  {% if nombre != 'nombre' %}
    <h4>La variable de la ruta es {{ nombre }}</h4>
  {% endif %}
  <p>
    Se pueden pasar mas de dos argumentos y estos por lo general se hace entre /, de la siguiente manera:
  </p>
  <pre>
    <code>
      @app.route('/bases/<<x>string:nombre>/<<x>int:dia>')
        def rutas(nombre, dia):
            ...
            return
    </code>
  </pre>
  <a class="float-right" href="{{ url_for('bases.debug') }}">Siguiente Pagina: Debug</a>
{% endblock content %}

Flask/Aplicacion/templates/venv.html
{% extends 'base.html' %}

{% block styles %}
  <title>Virtual enviroments</title>
{% endblock styles %}

{% block content %}
  <h2>Virtual environments y Pip</h2>
  <hr>
  <h4>Pip</h4>
  <p>Pip es el manejador de paquetes en python.</p>
    <br> 
    Para instalarlo en Ubuntu:
    <pre>

      $ sudo easy_install pip
      $ sudo pip install --upgrade pip
    </pre>
    Para instalarlo en MacOS:
    <pre>

      $ sudo easy_install pip
      $ sudo pip install --upgrade pip
    </pre>
    Para instalarlo en Windows:
    <pre>

      $ python get-pip.py
    </pre>  
    <p>
      Al igual que python a veces se corre como python o python3, igual pip o pip3.
    </p>
    <hr>
    <h4>Virtual environment</h4>
    <p>
      Ya que tenemos pip vamos a crear un virtual environment, estos nos sirven para que los paquetes que instalemos de pip 
      esten separados, muchas veces vamos a tener dos paginas con librerias diferentes  y no queremos que unas esten instaladas 
      en la otra pagina. Primero en la terminal se tiene que estar en el directorio donde la aplicacion va a estar.</p>
      <br>
      Para crear un nuevo enviroment:
      <pre>
        $ python3 -m venv nombre-del-env
      </pre>
      Para crear activarlo en Linux y MacOS:
      <pre>
        $ source nombre-del-env/bin/acivate
      </pre>
      Para crear activarlo en Windows:
      <pre>
        $ \env\Scripts\activate.bat
      </pre>
      <p>
        Ahora para crear la primera aplicacion de Flask, instalamos Flask (con el venv activado):
      </p>
      <pre>
        $ pip install flask
      </pre>
      <p>
        Creamos un archivo llamado app.py que contenga lo siguiente:
      </p>
      <pre class="language-python">
        <code>
          from flask import Flask

          app = Flask(__name__)
  
          @app.route('/')
          def index():
              return "Hola mundo"
  
          if "__name__" == __main__:
              app.run()</code>
      </pre>
      <p>
        Para correrlo:
      </p>
      <pre>
        python app.py
      </pre>
  <a class="float-right" href="{{ url_for('bases.rutas', nombre='nombre') }}">Siguiente Pagina: Rutas</a>
{% endblock content %}